### PR TITLE
Inference script optimization & removal of get_data scripts

### PR DESCRIPTION
**Pull request by HeliWang**
- Data source modification following Jimmy's assumption: 
   Assume that from `ONNX-demo`, [Castor-data](https://git.uwaterloo.ca/jimmylin/Castor-data) is checked out in `..`.

 - Add embedding path and seed as parameters to inference scripts.

### CODE REVIEW

**Comment by HeliWang** [comment]
Note the changes in README:

----------
### Docker Image Build
```
docker build --tag h379wang/kim-model-conversion .
```
### Run Docker Container
Assume that from `ONNX-demo`, [Castor-data](https://git.uwaterloo.ca/jimmylin/Castor-data) is checked out in `..` . Assume the current folder is `ONNX-demo`.
```
docker run -it -v $(pwd)/../Castor-data:/data h379wang/kim-model-conversion:latest /bin/bash
```
### Model Conversion
PyTorch -> ONNX -> MXNet Python -> MXNet Scala
```
source /opt/intel/bin/compilervars.sh intel64
python3 export_models.py
# Move the generated metadata of scala version of Kim Model
mv *.params scala_inference/
mv *.json scala_inference/
```
----------
### Inference Under Embedding Subset for SST-1 Dataset
##### PyTorch Inference of Kim Model
```
python3 pytorch_inference.py --embedding /data/embeddings/word2vec/word2vec.sst-1
```
##### MXNet Python Inference of Kim Model
```
source /opt/intel/bin/compilervars.sh intel64
python3 mxnet_inference.py --embedding /data/embeddings/word2vec/word2vec.sst-1
```
#####  MXNet Scala Inference of Kim Model
```
cd scala_inference
chmod +x prediction.sh
./prediction.sh
```
----------
### Inference Under Full Word2Vec Embedding
##### Create Full Word2Vec Embedding
Note that the convert_bin2txt.py process of converting the whole GoogleNews-vectors-negative300.bin embedding can take a long time.
```
python3 /app/kim_cnn/convert_bin2txt.py \
        /data/embeddings/word2vec/GoogleNews-vectors-negative300.bin \
        /data/embeddings/word2vec/word2vec.txt
```
##### PyTorch Inference of Kim Model
```
python3 pytorch_inference.py --embedding /data/embeddings/word2vec/word2vec.txt
```
##### MXNet Python Inference of Kim Model
```
source /opt/intel/bin/compilervars.sh intel64
python3 mxnet_inference.py --embedding /data/embeddings/word2vec/word2vec.txt
```
#####  MXNet Scala Inference of Kim Model
```
cd scala_inference
chmod +x prediction_full_embedding.sh
./prediction_full_embedding.sh
```

**Comment by HeliWang** [comment]
#### Also please merge https://git.uwaterloo.ca/jimmylin/Castor-data/merge_requests/9 before testing on this PR.

**Comment by lintool** [comment]
I've merged the `Castor-data` PR.

**Comment by HeliWang** [comment]
@r-clancy @Impavidity Any suggestion for the pull request? Message me if anything is missing here.

**Comment by HeliWang** [comment]
Close this pull request for now (no response from reviewers). Will make a new pull request for ONNX model inference in Spark and combine this PR.

**Comment by ryan-clancy** [comment]
@HeliWang I had made a comment to include the seed parameter in the `README`... include this in the next PR?

**Comment by HeliWang** [comment]
@ r-clancy I will follow up.

**Pull request closed without merging**
